apiVersion: apps/v1
kind: Deployment
metadata:
  name: messageservice
  labels:
    app: messageservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messageservice
  template:
    metadata:
      labels:
        app: messageservice
    spec:
      containers:
        - name: messageservice
          image: kwetters6.azurecr.io/messageservice:v0.1.4
          resources:
            limits:
              memory: 500Mi
              cpu: 500m
          ports:
            - containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: messageservice-service
spec:
  selector:
    app: messageservice
  ports:
    - protocol: TCP
      port: 5002

