version: '3.8'

services:
  mysql:
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_HOST: localhost
      MYSQL_DATABASE: Kwetter-MessageService
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3307:3306'
    expose:
      - '3307'
    volumes:
      - ./docker:/docker-entrypoint-initdb.d:z
  # user-management-service:
  #   depends_on: ["mysql"]
  #   image: user-management-service
  #   restart: unless-stopped
  #   build:
  #     context: ./src:/usr/src/
  #     target: dev
  #   volumes:
  #     - "./src:/usr/src/app/src"
  #   ports:
  #     - '4000:4000'
volumes:
  db-data:
