apiVersion: apps/v1
kind: Deployment
metadata:
  name: messageservice
  labels:
    app: messageservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messageservice
  template:
    metadata:
      labels:
        app: messageservice
    spec:
      containers:
        - name: messageservice
          image: localhost:5000/messageservice:v0.1.2
          ports:
            - containerPort: 5002
